Add constraints on invalid password attempts
vesoft-inc/nebula-docs pull request #1006
Opened 2022-01-05 07:02 UTC by cooper-lzy

2022-01-05 07:41 UTC, whitewum submitted a review, later dismissed

2022-01-07 10:20 UTC, randomJoe211 requested changes

2022-01-07 10:20 UTC, randomJoe211 commented on docs-2.0/7.data-security/1.authentication/1.authentication.md
> +1. Modify the `nebula-graphd.conf` file (`/usr/local/nebula/etc/` is the default path), set the parameters as followis:
```suggestion
1. Modify the `nebula-graphd.conf` file (`/usr/local/nebula/etc/` is the default path) to set the following parameters:
```

2022-01-07 10:20 UTC, randomJoe211 commented on docs-2.0/7.data-security/1.authentication/1.authentication.md
> +  - `--enable_authorize`: Whether to enable authentication, optional values are true or false.
```suggestion
  - `--enable_authorize`: Set its value to `true` to enable authentication.
```

Here we are telling the users how to enable authentication, not explaining the parameter.

2022-01-11 03:21 UTC, abby-cyber commented on docs-2.0/7.data-security/1.authentication/1.authentication.md
> +  - `--failed_login_attempts`: The parameter is optional, you need to add this parameter manually. The number of consecutive incorrect passwords allowed by a single Graph service. When the number exc
```suggestion
  - `--failed_login_attempts`: This parameter is optional, and you need to add this parameter manually. Specify the attempts of continuously entering incorrect passwords for a single Graph service. When the number exceeds the limitation, your account will be locked. For multiple Graph services, the allowed attempts are `number of services * failed_login_attempts`.
```

2022-01-11 03:21 UTC, abby-cyber commented on docs-2.0/7.data-security/1.authentication/1.authentication.md
> +  - `--password_lock_time_in_secs`: The parameter is optional, you need to add this parameter manually. Duration of account locking after multiple incorrect passwords is entered. Unit: second.
```suggestion
  - `--password_lock_time_in_secs`: This parameter is optional, and you need to add this parameter manually. Specify the time how long your account is locked after multiple incorrect password entries are entered. Unit: second.
```

2022-01-12 08:08 UTC, foesa-yang approved these changes

2022-01-13 03:46 UTC, abby-cyber approved these changes

2022-01-13 03:49 UTC, randomJoe211 approved these changes

2022-01-13 03:49 UTC, merged