Add note for more clients
vesoft-inc/nebula-docs pull request #1218
Opened 2022-03-31 09:23 UTC by abby-cyber

2022-03-31 09:57 UTC, whitewum requested changes

2022-03-31 09:57 UTC, whitewum commented on docs-2.0/14.client/1.nebula-client.md
> +    Other clients（such as [Nebula PHP](https://github.com/nebula-contrib/nebula-php), [Nebula Node](https://github.com/nebula-contrib/nebula-node), [Nebula .net](https://github.com/nebula-contrib/neb
non-english (

2022-04-07 06:25 UTC, whitewum approved these changes

2022-04-07 07:36 UTC, randomJoe211 approved these changes

2022-04-07 07:36 UTC, merged