full-doc changes for dashboard
vesoft-inc/nebula-docs pull request #1249
Opened 2022-04-15 06:30 UTC by abby-cyber

2022-04-21 06:51 UTC, whitewum approved these changes

2022-04-21 07:57 UTC, randomJoe211 requested changes
Complete the unfinished sentence, please.

2022-04-21 07:57 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard-ent/3.create-import-dashboard/2.import-cluster.md
> +   - **Authorize** the node. The SSH username and password of each node are required, and choose
Unfinished sentence?

2022-04-21 07:57 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard-ent/4.cluster-operator/1.overview.md
> +In the **Alert** section, the system displays the five most recently triggered alert messages according to their severity level (`emergency`>`critical`>`warning`).
```suggestion
In the **Alert** section, the system displays the five most recently triggered alert messages according to their severity levels (`emergency`>`critical`>`warning`). 
```

2022-04-21 07:57 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard-ent/4.cluster-operator/1.overview.md
> +        The parameter **Expiration Time** is displayed only if the created or imported cluster is an Enterprise Edition.
"Cluster is an Enterprise Edition"?

Consider:

The parameter **Expiration Time** is displayed only if the created or imported cluster is an Enterprise Edition cluster.
or
The parameter **Expiration Time** is displayed for only Enterprise Edition clusters.

2022-04-21 07:57 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard-ent/4.cluster-operator/1.overview.md
> +- **Creator**：The Dashboard account that used to create the cluster.
```suggestion
- **Creator**：The Dashboard account that is used to create the cluster. 
```

Or just "account used".

2022-04-21 07:57 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard-ent/4.cluster-operator/1.overview.md
> +In the upper right of the **Information** section, click ![watch](https://docs-cdn.nebula-graph.com.cn/figures/watch.png) to view the cluster details, including name, creation time, account name, ver
```suggestion
In the upper right of the **Information** section, click ![watch](https://docs-cdn.nebula-graph.com.cn/figures/watch.png) to view the cluster details, including name, creation time, account name, version, and the role of the account name.
```

2022-04-21 07:57 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard-ent/4.cluster-operator/1.overview.md
> +    - Displays the license details of the cluster, including the usage status, the organization, the creation time, the expiration time, and the cluster versions supported by the license, and the lic
```suggestion
    - Displays the license details of the cluster, including the usage status, the organization, the creation time, the expiration time, the cluster versions supported by the license, and the license type.
```

2022-04-22 02:07 UTC, whitewum approved these changes

2022-04-22 06:21 UTC, randomJoe211 approved these changes

2022-04-22 06:21 UTC, merged