update analytics 1.1.0
vesoft-inc/nebula-docs pull request #1253
Opened 2022-04-18 06:37 UTC by cooper-lzy

### What is changed, added or deleted? (Required)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

2022-04-20 10:12 UTC, whitewum requested changes

2022-04-20 10:12 UTC, whitewum commented on docs-2.0/nebula-analytics.md
> +|  PageRankLDBC          | Rank web pages compatible with LDBC   | Node importance measurement  |
what is PageRankLDBC? This is not a standard page rank algorithm.
It is temporary? or use URL link to explain the algorithm.

2022-04-22 02:06 UTC, whitewum approved these changes

2022-04-22 03:48 UTC, abby-cyber approved these changes

2022-04-22 03:48 UTC, merged