full-docs changes for operator 1.1.0
vesoft-inc/nebula-docs pull request #1256
Opened 2022-04-19 03:42 UTC by abby-cyber

2022-04-20 10:17 UTC, whitewum submitted a review, later dismissed

2022-04-21 05:49 UTC, randomJoe211 commented on docs-2.0/nebula-operator/1.introduction-to-nebula-operator.md
> +- **Cluster Upgrade**: Nebula Operator supports cluster upgrading from version {{upgrade_from}} to version {{upgrade_to}}.
Wrong macro formats.
operator.upgrade_from
operator.upgrade_to

2022-04-21 05:50 UTC, randomJoe211 commented on docs-2.0/nebula-operator/1.introduction-to-nebula-operator.md
> +    - Starting from Nebula Operator 0.9.0, logs and data are stored separately. Using Nebula Operator 0.9.0 or later versions to manage a Nebula Graph 2.5.x cluster created with Operator 0.8.0  can c
```suggestion
    - Starting from Nebula Operator 0.9.0, logs and data are stored separately. Using Nebula Operator 0.9.0 or later versions to manage a Nebula Graph 2.5.x cluster created with Operator 0.8.0 can cause compatibility issues. You can backup the data of the Nebula Graph 2.5.x cluster and then create a 2.6.x cluster with Operator 0.9.0.
```

2022-04-21 06:02 UTC, foesa-yang approved these changes

2022-04-21 06:07 UTC, randomJoe211 submitted a review, later dismissed

2022-04-21 06:07 UTC, randomJoe211 commented on docs-2.0/nebula-operator/9.upgrade-nebula-cluster.md
> +- Only for Nebula Graph clusters that were created with Nebula Operator.
No need to use the the past tense.

2022-04-21 06:13 UTC, whitewum requested changes
should be english only

2022-04-21 06:13 UTC, whitewum commented on docs-2.0/20.appendix/6.eco-tool-version.md
> +|Nebula Graph 版本|Operator 版本|
English...

2022-04-21 06:53 UTC, whitewum submitted a review, later dismissed

2022-04-21 07:19 UTC, foesa-yang approved these changes

2022-04-21 07:19 UTC, randomJoe211 approved these changes

2022-04-21 07:19 UTC, merged