Update 1.nebula-client.md
vesoft-inc/nebula-docs pull request #1407
Opened 2022-06-06 02:38 UTC by abby-cyber

2022-06-07 01:12 UTC, cooper-lzy approved these changes

2022-06-09 08:33 UTC, whitewum requested changes

2022-06-09 08:33 UTC, whitewum commented on docs-2.0/14.client/1.nebula-client.md
> +      - [NORM（Nebula Graph's Golang ORM）](https://github.com/zhihu/norm)
() not   （）

2022-06-10 03:51 UTC, randomJoe211 commented on docs-2.0/14.client/1.nebula-client.md
> +      - [NORM（Nebula Graph's Golang ORM）](https://github.com/zhihu/norm)
```suggestion
      - [NORM (Nebula Graph's Golang ORM)](https://github.com/zhihu/norm)
```

2022-06-10 03:52 UTC, randomJoe211 commented on docs-2.0/14.client/1.nebula-client.md
> +      - [Graph-Ocean（Nebula Graph's Java ORM）](https://github.com/nebula-contrib/graph-ocean)
```suggestion
      - [Graph-Ocean (Nebula Graph's Java ORM)](https://github.com/nebula-contrib/graph-ocean)
```

2022-06-10 03:53 UTC, randomJoe211 approved these changes

2022-06-10 07:11 UTC, whitewum approved these changes

2022-06-10 07:11 UTC, merged