port-faq
vesoft-inc/nebula-docs pull request #166
Opened 2020-10-22 02:46 UTC by Amber1990Zhang

2020-10-22 02:46 UTC, darionyaphet approved these changes

2020-10-22 03:23 UTC, whitewum reviewed
It's not all that I want.
I also hope to list all the usage ports and their default value.

2020-10-22 03:25 UTC, whitewum requested changes
please list all the ports in use

like:

please check the following ports are available, and not blocked by your firewall. you can find them in the config file in ....

Besides, if you change the default value of the ports, remember to restart the services.

metad: 
45500,11000,11002

storaged:
44500, ...

graphd:
3699, ...

2020-10-27 05:58 UTC, randomJoe211 approved these changes

2020-10-27 06:01 UTC, jievince approved these changes

2020-10-27 06:01 UTC, merged