Add dmp file and change forum addresses
vesoft-inc/nebula-docs pull request #1836
Opened 2022-12-30 06:19 UTC by foesa-yang

### What is changed, added or deleted? (Required)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

2022-12-30 08:55 UTC, whitewum requested changes

2022-12-30 08:55 UTC, whitewum commented on docs-2.0/1.introduction/1.what-is-nebula-graph.md
> +Written in C++ and born for graphs, NebulaGraph handles graph queries in milliseconds. Among most databases, NebulaGraph shows superior performance in providing graph data services. The larger the da
discussionst typo

2023-01-03 02:53 UTC, abby-cyber approved these changes

2023-01-05 05:39 UTC, cooper-lzy approved these changes

2023-01-06 05:36 UTC, whitewum approved these changes

2023-01-06 05:36 UTC, merged