translation
vesoft-inc/nebula-docs pull request #503
Opened 2021-05-20 09:15 UTC by FengUyu

2021-05-24 04:04 UTC, whitewum submitted a review, later dismissed

2021-05-24 08:19 UTC, randomJoe211 requested changes

2021-05-24 08:19 UTC, randomJoe211 commented on docs-2.0/nebula-studio/about-studio/st-ug-what-is-graph-studio.md
> +For Docker-based and RPM-based Studio, authentication is not enabled in Nebula Graph by default and you can sign in to Studio with the default account and password (`user` and `password`) to log in t
This sentence is too long. And there seems to be a logical issue: sign into Studio and log into Studio? Double-check it.

2021-05-24 10:26 UTC, whitewum approved these changes

2021-05-25 01:54 UTC, randomJoe211 approved these changes

2021-05-25 02:19 UTC, whitewum approved these changes

2021-05-25 02:19 UTC, merged