path
vesoft-inc/nebula-docs pull request #530
Opened 2021-06-24 06:24 UTC by izhuxiaoqing

2021-06-24 06:27 UTC, whitewum requested changes
2 figs ...

2021-06-24 06:27 UTC, whitewum commented on docs-2.0/1.introduction/2.1.path.md
> +![path graph](../20.appendix/path.png)
you might forget copy this file.

2021-06-24 06:27 UTC, whitewum commented on docs-2.0/1.introduction/2.1.path.md
> +![trail graph](../20.appendix/Circuits.png)
ditto

2021-06-24 08:17 UTC, randomJoe211 commented on docs-2.0/1.introduction/2.1.path.md
> +In the above path graph, edges cannot be repeatedly visited. So, this path graph contains finite paths. The longest path in this graph consists of 5 edges: `A->B->C->D->E->C`.
There is no such thing as a path graph. Let's make it clear:

* A graph is a graph in graph theory. Graphs have vertices and edges.
* A picture or figure is, well, something like an image or a drawing.

So, maybe we should use "In the above picture/figure"? WDYT?

2021-06-24 08:17 UTC, randomJoe211 commented on docs-2.0/1.introduction/2.1.path.md
> +A `path` is a finite sequence of edges. Neither vertices or edges can be repeatedly visited in graph traversal.
Neither vertices nor edges

2021-06-24 08:17 UTC, randomJoe211 commented on docs-2.0/1.introduction/2.1.path.md
> +So, the above path graph contains finite paths. The longest path in this graph consists of 4 edges: `A->B->C->D->E`.
Not path graph.

Check through the topic plz.

2021-06-24 08:17 UTC, randomJoe211 commented on docs-2.0/1.introduction/2.1.path.md
> +There are two special cases of trail, `cycle` and `circuit`. The following picture is an example for a brief introduction.
, and `circuit`

2021-06-24 09:39 UTC, randomJoe211 submitted a review, later dismissed

2021-06-24 09:41 UTC, randomJoe211 submitted a review, later dismissed

2021-06-24 10:05 UTC, FengUyu submitted a review, later dismissed

2021-06-24 10:53 UTC, whitewum commented
waiting for the png files being moved

2021-06-25 01:09 UTC, cooper-lzy approved these changes

2021-06-25 03:16 UTC, whitewum approved these changes

2021-06-25 03:16 UTC, merged