start stop service
vesoft-inc/nebula-docs pull request #546
Opened 2021-07-06 10:23 UTC by izhuxiaoqing

2021-07-07 11:22 UTC, randomJoe211 requested changes

2021-07-07 11:22 UTC, randomJoe211 commented on docs-2.0/2.quick-start/5.start-stop-service.md
> +Nebula Graph uses the `nebula.service` script to start, stop, restart, terminate, and check the Nebula Graph services. This topic takes starting, stopping and checking the Nebula Graph services for e
The `nebula.service` script can start, stop, restart, terminate, and check the Nebula Graph services. So the subject of the first sentence cannot be Nebula Graph, which is already the object.

2021-07-07 11:22 UTC, randomJoe211 commented on docs-2.0/2.quick-start/5.start-stop-service.md
> +About non-container deployment, users can see [Install Nebula Graph with RPM or DEB package](../4.deployment-and-installation/2.compile-and-install-nebula-graph/2.install-nebula-graph-by-rpm-or-deb.m
```suggestion
About non-container deployment, see [Install Nebula Graph with RPM or DEB package](../4.deployment-and-installation/2.compile-and-install-nebula-graph/2.install-nebula-graph-by-rpm-or-deb.md). Run the following command to start Nebula Graph.
```

2021-07-07 11:22 UTC, randomJoe211 commented on docs-2.0/2.quick-start/5.start-stop-service.md
> +* Nebula Graph service is running normally if the following information is returned.
Service is not necessary here. If you wish to keep it, at least use services because there are 3 different services in the following code block.

2021-07-07 11:22 UTC, randomJoe211 commented on docs-2.0/2.quick-start/5.start-stop-service.md
> +* If the returned information is similar to the following one, there may be a problem. Users can check the corresponding information to troubleshoot problems or go to [Nebula Graph Forum](https://dis
It is not a may-be. It is a must-be.

2021-07-08 03:38 UTC, randomJoe211 approved these changes

2021-07-08 03:52 UTC, whitewum approved these changes

2021-07-08 03:52 UTC, merged