monitor parameter
vesoft-inc/nebula-docs pull request #564
Opened 2021-07-21 02:32 UTC by izhuxiaoqing

2021-07-21 03:28 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`cpu_system`| The percentage of CPU used by the system (not the kernel space of Nebula Graph). |
```suggestion
|`cpu_user`| The percentage of CPU used by users |
|`cpu_system`| The percentage of CPU used by the system |
```

And remove all periods at the end of phrases.

2021-07-21 03:28 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`memory_actual_used`| The memory that is in actual use. |
Clarify these two.

2021-07-21 03:28 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`memory_free`| The memory that is idled. |
Add the size of to this part? Like The size of free memory.

2021-07-21 03:35 UTC, whitewum approved these changes

2021-07-21 03:48 UTC, randomJoe211 requested changes

2021-07-21 03:48 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`memory_used`| The memory that is used. |
The size of used memory or The memory space used?

2021-07-21 03:48 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`disk_used`| The disk that is used. |
The disk space?

2021-07-21 03:48 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`disk_writebytes`| The number of bytes that the disk writes every second. |
The subject should be the system.

2021-07-21 03:48 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`network_out_packets`| The number of data packages that the network sends out every second. |
Network card?

2021-07-21 03:48 UTC, randomJoe211 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`get_neighbors_latency_us`| Query the average latency of neighbors. |
Double-check this part.

2021-07-21 06:54 UTC, randomJoe211 approved these changes

2021-07-21 07:11 UTC, Kun8018 commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`network_out_packets`| The number of data packages that the network card sends out every second. |
replace every with per is better?~

2021-07-21 07:14 UTC, Kun8018 approved these changes

2021-07-22 02:22 UTC, Aiee commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`memory_free`| The memory space idled. |
The memory space that is available.

2021-07-22 02:22 UTC, Aiee commented on docs-2.0/nebula-dashboard/6.monitor-parameter.md
> +|`disk_free`| The disk space idled. |
ditto.

2021-07-22 06:27 UTC, whitewum approved these changes

2021-07-23 02:35 UTC, whitewum approved these changes

2021-07-23 03:09 UTC, whitewum approved these changes

2021-07-26 08:33 UTC, randomJoe211 approved these changes

2021-07-26 08:33 UTC, merged