update studio manage schema
vesoft-inc/nebula-docs pull request #648
Opened 2021-08-30 08:35 UTC by foesa-yang

2021-08-30 08:44 UTC, whitewum approved these changes

2021-08-31 02:18 UTC, randomJoe211 requested changes

2021-08-31 02:18 UTC, randomJoe211 commented on docs-2.0/nebula-studio/manage-schema/st-ug-crud-index.md
> +   d. **Indexed Properties**: Click **Add**, and then, in the dialog box, choose a property. If necessary, repeat this step to choose more properties. You can drag the properties to sort them. In thi
```suggestion
   d. **Indexed Properties**: Click **Add**, and then, in the dialog box, choose a property. If necessary, repeat this step to choose more properties. You can drag the properties to sort them. In this example, `degree` is chosen.
```

2021-08-31 02:18 UTC, randomJoe211 commented on docs-2.0/nebula-studio/manage-schema/st-ug-crud-index.md
> +   e. **Comment**: The remarks of a certain property or the index itself. The maximum length is 256 bytes. By default, there will be no comments on a index, `follow_index` is used.
"By default, there will be no comments on a index, `follow_index` is used."
Something wrong with the logic of this sentence. Please double-check it.
And it should be "no comments on an index".

2021-08-31 02:18 UTC, randomJoe211 commented on docs-2.0/nebula-studio/manage-schema/st-ug-crud-space.md
> +   c. **Comment**: The remarks of a certain property or the space itself. The maximum length is 256 bytes. By default, there will be no comments on a space, `Statistics of basketball players` is used
Same issue. Why "there will be no comments on a space" then "`Statistics of basketball players` is used"? What is their connection?

2021-08-31 02:32 UTC, whitewum approved these changes

2021-08-31 02:39 UTC, whitewum approved these changes

2021-08-31 03:17 UTC, whitewum approved these changes

2021-08-31 03:17 UTC, whitewum commented on docs-2.0/nebula-studio/manage-schema/st-ug-crud-space.md
> +    Deleting the Space will delete all the data in it, and the deleted data cannot be restored if it is not [backed up](../../7.data-security/3.manage-snapshot.md).
space

2021-08-31 09:54 UTC, whitewum approved these changes

2021-09-01 02:15 UTC, izhuxiaoqing approved these changes

2021-09-01 09:33 UTC, randomJoe211 approved these changes

2021-09-01 09:33 UTC, merged